### ISSUE TITLE
Post the complete JavaScript code, not just the min version.

### ISSUE THREAD

**Issue by franciscocorrales** [rithychhen88/birthday-picker#3]
In order to contribute to this project, it would be better to add the complete JavaScript version, the whole source files. I will also make it more readable, and be able to check on bugs.

**Comment by bobbyschultz** [comment]
http://unminify.com

**Comment by franciscocorrales** [comment]
@bobbyschultz That makes it pretty. But we still loose comments and variable names.

**Comment by rovarellasbt** [comment]
Any progress?

**Comment by rithychhen88** [comment]
I have posted the unminify version. Thanks.
