### ISSUE TITLE
Picker doesn't have value until it is changed by user.

### ISSUE THREAD

**Issue by franciscocorrales** [rithychhen88/birthday-picker#4]
The input doesn't have value until the user changes one of the inputs.

Even though, I'm setting the `defaultDate` to a date, and it shows the pickers well. But when I try to get the value from day picker, it doesn't have any.

This is how it looks:
<input class="birthDay" name="birthDay" type="hidden">

**Comment by bobbyschultz** [comment]
This is a problem especially when repopulating a form after a failed validation attempt. I can repopulate the birthday using defaultDate in the jQuery, but when the form is re-submitted, no birthdate data is passed.

**Comment by rithychhen88** [comment]
The issue has been fixed. New code has been added to the repo.

**Comment by franciscocorrales** [comment]
Just for you to know, you didn't update the `jquery-birthday-picker.min.js` version of the file.
