### ISSUE TITLE
Date doesn't start on 0 like the standard JavaScript Date.

### ISSUE THREAD

**Issue by franciscocorrales** [rithychhen88/birthday-picker#5]
The starting day and month doesn't start on 0, as the official JavaScript standard. 

This leads to weird things, like having to do somethings like:
`ufdate.getDate() + 1`
`ufdate.getMonth()+1`

https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by rithychhen88** [comment]
Not sure what you are trying to accomplish here.
