### ISSUE TITLE
(Chrome) Uncaught TypeError: Cannot read property 'replace' of undefined 

### ISSUE THREAD

**Issue by franciscocorrales** [rithychhen88/birthday-picker#7]
Browser: Chrome

The error happens on the function: `generateBirthdayPicker`, on the line:  
`var parentId = $parent.attr('id').replace(/-/g, '');`

Take a look at the image.

![captura](https://cloud.githubusercontent.com/assets/4010693/11906793/da1552ba-a594-11e5-8836-ab294c074c8e.PNG)

**Comment by rithychhen88** [comment]
Hey thank for you feature. $parent is actually a jquery selector. It's not parent. In this case $parent would be your selected element. Example $(".test").birthdayPickert().  $parent is $('.test').  It is complaining because your <code> div class='test' </code> doesn't have an id.
