### ISSUE TITLE
Datepickert doesn't initialize on Firefox v42.0

### ISSUE THREAD

**Issue by franciscocorrales** [rithychhen88/birthday-picker#8]
Doesn't work for Firefox, you can even check it on your demo page:
http://www.rithychhen.com/jquery/birthdaypicker

My setup:
Firefox 42.0

**Comment by rithychhen88** [comment]
I will take a look thank,

**Comment by franciscocorrales** [comment]
The problem is cause Firefox is not as flexible as creating dates.

So, this line:
`var date = new Date(options.defaultDate);`
Doesn't create a valid date!

**Solution:**
Changed input date format from
`"01-01-2016"` to `"01/01/2016"`

**Comment by rithychhen88** [comment]
yeah that what i thought.
