### ISSUE TITLE
How can I get the current date value ?

### ISSUE THREAD

**Issue by franciscocorrales** [rithychhen88/birthday-picker#9]
Maybe a silly question, but I can't find how to do this on the documentation.

In any given moment, how can I get the current date value ?.

I've done things like: `jQuery('#DateOfBirth .birthDay').val(),` but it holds the date used to initialize the datepicker.

The **problem** is that this line:
`$selector.val(hiddenDate);`
Its not updating the input value

Note: When I change the date, none of the HTML code gets updated. So, I don't know, where the datepicker is updating the new date.

**Comment by franciscocorrales** [comment]
More data:

Inital date:
![captura](https://cloud.githubusercontent.com/assets/4010693/12521143/63ab2bfa-c10e-11e5-8007-ff8814f89cba.PNG)

I changed to
`"02/02/2014"`

The screen does looks good:
![captura](https://cloud.githubusercontent.com/assets/4010693/12521093/2348254a-c10e-11e5-94a3-dff6773f4619.PNG)

But if I do:
`jQuery('#DateOfBirth .birthDay').val()`
I get: `"2009-10-10"` :(

Here is the HTML:
`
<div id="DateOfBirth" class="DateOfBirth" data-wcp_birthdate="2009-09-09T00:00:00"><fieldset class="birthdayPicker"><select class="birthMonth span2 valid" name="DateOfBirth_birth[month]" aria-invalid="false"><option value="0">Month</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option></select><select class="birthDate span2 valid" name="DateOfBirth_birth[day]" aria-invalid="false"><option value="0">Day</option><option value="1">01</option><option value="2">02</option><option value="3">03</option><option value="4">04</option><option value="5">05</option><option value="6">06</option><option value="7">07</option><option value="8">08</option><option value="9">09</option><option value="10">10</option><option value="11">11</option><option value="12">12</option><option value="13">13</option><option value="14">14</option><option value="15">15</option><option value="16">16</option><option value="17">17</option><option value="18">18</option><option value="19">19</option><option value="20">20</option><option value="21">21</option><option value="22">22</option><option value="23">23</option><option value="24">24</option><option value="25">25</option><option value="26">26</option><option value="27">27</option><option value="28">28</option></select><select class="birthYear span2 valid" name="DateOfBirth_birth[year]" aria-invalid="false"><option value="0">Year</option><option value="2016">2016</option><option value="2015">2015</option><option value="2014">2014</option><option value="2013">2013</option><option value="2012">2012</option><option value="2011">2011</option><option value="2010">2010</option><option value="2009">2009</option><option value="2008">2008</option><option value="2007">2007</option><option value="2006">2006</option><option value="2005">2005</option><option value="2004">2004</option><option value="2003">2003</option><option value="2002">2002</option><option value="2001">2001</option><option value="2000">2000</option><option value="1999">1999</option><option value="1998">1998</option><option value="1997">1997</option><option value="1996">1996</option><option value="1995">1995</option><option value="1994">1994</option><option value="1993">1993</option><option value="1992">1992</option><option value="1991">1991</option><option value="1990">1990</option><option value="1989">1989</option><option value="1988">1988</option><option value="1987">1987</option><option value="1986">1986</option><option value="1985">1985</option><option value="1984">1984</option><option value="1983">1983</option><option value="1982">1982</option><option value="1981">1981</option><option value="1980">1980</option><option value="1979">1979</option><option value="1978">1978</option><option value="1977">1977</option><option value="1976">1976</option><option value="1975">1975</option><option value="1974">1974</option><option value="1973">1973</option><option value="1972">1972</option><option value="1971">1971</option><option value="1970">1970</option><option value="1969">1969</option><option value="1968">1968</option><option value="1967">1967</option><option value="1966">1966</option><option value="1965">1965</option><option value="1964">1964</option><option value="1963">1963</option><option value="1962">1962</option><option value="1961">1961</option><option value="1960">1960</option><option value="1959">1959</option><option value="1958">1958</option><option value="1957">1957</option><option value="1956">1956</option><option value="1955">1955</option><option value="1954">1954</option><option value="1953">1953</option><option value="1952">1952</option><option value="1951">1951</option><option value="1950">1950</option><option value="1949">1949</option><option value="1948">1948</option><option value="1947">1947</option><option value="1946">1946</option><option value="1945">1945</option><option value="1944">1944</option><option value="1943">1943</option><option value="1942">1942</option><option value="1941">1941</option><option value="1940">1940</option><option value="1939">1939</option><option value="1938">1938</option><option value="1937">1937</option><option value="1936">1936</option><option value="1935">1935</option><option value="1934">1934</option><option value="1933">1933</option><option value="1932">1932</option><option value="1931">1931</option><option value="1930">1930</option><option value="1929">1929</option><option value="1928">1928</option><option value="1927">1927</option><option value="1926">1926</option><option value="1925">1925</option><option value="1924">1924</option><option value="1923">1923</option><option value="1922">1922</option><option value="1921">1921</option><option value="1920">1920</option><option value="1919">1919</option><option value="1918">1918</option><option value="1917">1917</option><option value="1916">1916</option></select><input class="birthDay" name="DateOfBirth_birthDay" type="hidden" value="2009-10-10"></fieldset></div>`

**Comment by rithychhen88** [comment]
use the callback property to get the current selected value. Here is an example. 

$("#max-year-birthday").birthdayPicker({
                    "defaultDate": "01-03-1980",
                    "maxYear": "2020",
                    "maxAge": 65,
                    'callback': function(value) {
                        console.log(value);
                    }
                });

**Comment by franciscocorrales** [comment]
1. But what about the problem, that the value attribute is not being updated ?. I think that's a real bug. I haven't been able to fix that. Not sure why....
2. I noticed about the callback. But a callback is not always the way to go, when you need to get the date value. Example: I have a form with a list of dates, and I need to get all dates data, wrap it with the other fields, then submit it to the server. I think callback is not good for this case. There should be a way to retrieve the date value as needed by the programmer.

**Comment by rithychhen88** [comment]
The value does update. In case u want multiple date to be submit to the backend, you just have to place all the birthday picked in a form.. Submitting the form will carry those values.. Get them from the post on your server side

**Comment by franciscocorrales** [comment]
I'm not getting the HTML value being updated.

This is my initialized HTML:
`<input class="birthDay" name="DateOfBirth_birthDay" type="hidden" value="2009-10-10">`
It never changes.

Are we using the same HTML element ?

**Comment by rithychhen88** [comment]
hmm. i will take a look as soon as i can.

**Comment by rithychhen88** [comment]
There is a bug, it has been fixed.

**Comment by franciscocorrales** [comment]
Checked. Working as expected.

Thanks !
